// Mock Users - Beautiful profiles with real-looking data
export const mockUsers = [
  {
    _id: "mock1",
    username: "sarah_johnson",
    profilePicture: "https://i.pravatar.cc/150?img=1",
    coverPicture: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&h=400&fit=crop",
    desc: "Travel blogger ✈️ | Coffee addict ☕ | Living my best life",
    city: "San Francisco",
    from: "California",
    followers: ["mock2", "mock3", "mock4"],
    followings: ["mock5", "mock6"],
  },
  {
    _id: "mock2",
    username: "alex_marvel",
    profilePicture: "https://i.pravatar.cc/150?img=12",
    coverPicture: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=400&fit=crop",
    desc: "Software Engineer 💻 | Tech enthusiast | Building cool stuff",
    city: "New York",
    from: "New York",
    followers: ["mock1", "mock3"],
    followings: ["mock4", "mock7"],
  },
  {
    _id: "mock3",
    username: "emma_creative",
    profilePicture: "https://i.pravatar.cc/150?img=5",
    coverPicture: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&h=400&fit=crop",
    desc: "Digital Artist 🎨 | UI/UX Designer | Making the web beautiful",
    city: "Los Angeles",
    from: "California",
    followers: ["mock1", "mock2", "mock5"],
    followings: ["mock6", "mock8"],
  },
  {
    _id: "mock4",
    username: "mike_fitness",
    profilePicture: "https://i.pravatar.cc/150?img=13",
    coverPicture: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=400&fit=crop",
    desc: "Fitness Coach 💪 | Nutrition Expert | Transform your life",
    city: "Miami",
    from: "Florida",
    followers: ["mock2", "mock6"],
    followings: ["mock1", "mock9"],
  },
  {
    _id: "mock5",
    username: "lisa_foodie",
    profilePicture: "https://i.pravatar.cc/150?img=9",
    coverPicture: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=400&fit=crop",
    desc: "Food Blogger 🍕 | Recipe Creator | Making delicious memories",
    city: "Chicago",
    from: "Illinois",
    followers: ["mock3", "mock4", "mock7"],
    followings: ["mock2", "mock10"],
  },
  {
    _id: "mock6",
    username: "david_photo",
    profilePicture: "https://i.pravatar.cc/150?img=14",
    coverPicture: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&h=400&fit=crop",
    desc: "Photographer 📸 | Visual Storyteller | Capturing moments",
    city: "Seattle",
    from: "Washington",
    followers: ["mock1", "mock5", "mock8"],
    followings: ["mock3", "mock4"],
  },
  {
    _id: "mock7",
    username: "jennifer_yoga",
    profilePicture: "https://i.pravatar.cc/150?img=16",
    coverPicture: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=400&fit=crop",
    desc: "Yoga Instructor 🧘 | Mindfulness Coach | Find your zen",
    city: "Austin",
    from: "Texas",
    followers: ["mock2", "mock5"],
    followings: ["mock6", "mock9"],
  },
  {
    _id: "mock8",
    username: "chris_music",
    profilePicture: "https://i.pravatar.cc/150?img=15",
    coverPicture: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=400&fit=crop",
    desc: "Music Producer 🎵 | DJ | Creating vibes",
    city: "Nashville",
    from: "Tennessee",
    followers: ["mock3", "mock6"],
    followings: ["mock1", "mock7"],
  },
  {
    _id: "mock9",
    username: "olivia_style",
    profilePicture: "https://i.pravatar.cc/150?img=10",
    coverPicture: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&h=400&fit=crop",
    desc: "Fashion Stylist 👗 | Beauty Influencer | Style is everything",
    city: "Boston",
    from: "Massachusetts",
    followers: ["mock4", "mock7", "mock8"],
    followings: ["mock5", "mock10"],
  },
  {
    _id: "mock10",
    username: "ryan_ventures",
    profilePicture: "https://i.pravatar.cc/150?img=17",
    coverPicture: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=400&fit=crop",
    desc: "Entrepreneur 🚀 | Startup Founder | Building the future",
    city: "Denver",
    from: "Colorado",
    followers: ["mock5", "mock9"],
    followings: ["mock2", "mock8"],
  },
];

// Mock Posts - Beautiful posts with real images
export const mockPosts = [
  {
    _id: "post1",
    userId: "mock1",
    username: "sarah_johnson",
    userProfilePic: "https://i.pravatar.cc/150?img=1",
    desc: "Just landed in Bali! 🌴 This place is absolutely magical. Can't wait to explore the beaches and temples!",
    img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=600&fit=crop",
    likes: ["mock2", "mock3", "mock4", "mock5", "mock8"],
    reactions: {
      like: ["mock2", "mock3"],
      love: ["mock4", "mock5"],
      wow: ["mock8"],
    },
    comments: [
      {
        _id: "c1",
        userId: "mock3",
        username: "emma_creative",
        userProfilePic: "https://i.pravatar.cc/150?img=5",
        text: "Wow! So beautiful! Have an amazing time! 😍",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
      },
      {
        _id: "c2",
        userId: "mock2",
        username: "alex_marvel",
        userProfilePic: "https://i.pravatar.cc/150?img=12",
        text: "Bali is on my bucket list! Enjoy every moment!",
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1 hour ago
      },
    ],
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000), // 3 hours ago
  },
  {
    _id: "post2",
    userId: "mock2",
    username: "alex_marvel",
    userProfilePic: "https://i.pravatar.cc/150?img=12",
    desc: "New project launch! 🚀 Spent the last 6 months building this. Finally going live today! #coding #startup",
    img: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    likes: ["mock1", "mock3", "mock6", "mock7"],
    reactions: {
      like: ["mock1", "mock3"],
      love: ["mock6"],
      wow: ["mock7"],
    },
    comments: [
      {
        _id: "c3",
        userId: "mock1",
        username: "sarah_johnson",
        userProfilePic: "https://i.pravatar.cc/150?img=1",
        text: "Congratulations! This is huge! 🎉",
        createdAt: new Date(Date.now() - 30 * 60 * 1000), // 30 min ago
      },
    ],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
  },
  {
    _id: "post3",
    userId: "mock3",
    username: "emma_creative",
    userProfilePic: "https://i.pravatar.cc/150?img=5",
    desc: "New UI design for a fintech app! What do you think? 🎨 Feedback is always welcome!",
    img: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop",
    likes: ["mock1", "mock2", "mock4", "mock6", "mock8", "mock9"],
    reactions: {
      like: ["mock1", "mock2", "mock4"],
      love: ["mock6", "mock8"],
      wow: ["mock9"],
    },
    comments: [
      {
        _id: "c4",
        userId: "mock2",
        username: "alex_marvel",
        userProfilePic: "https://i.pravatar.cc/150?img=12",
        text: "Clean design! Love the color palette 🎨",
        createdAt: new Date(Date.now() - 45 * 60 * 1000),
      },
      {
        _id: "c5",
        userId: "mock6",
        username: "david_photo",
        userProfilePic: "https://i.pravatar.cc/150?img=14",
        text: "This is fire! 🔥",
        createdAt: new Date(Date.now() - 20 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    _id: "post4",
    userId: "mock4",
    username: "mike_fitness",
    userProfilePic: "https://i.pravatar.cc/150?img=13",
    desc: "Morning workout complete! 💪 Remember: The only bad workout is the one you didn't do. Let's get it!",
    img: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop",
    likes: ["mock2", "mock5", "mock7", "mock9"],
    reactions: {
      like: ["mock2", "mock5"],
      love: ["mock7", "mock9"],
    },
    comments: [
      {
        _id: "c6",
        userId: "mock7",
        username: "jennifer_yoga",
        userProfilePic: "https://i.pravatar.cc/150?img=16",
        text: "You're an inspiration! 💪",
        createdAt: new Date(Date.now() - 15 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    _id: "post5",
    userId: "mock5",
    username: "lisa_foodie",
    userProfilePic: "https://i.pravatar.cc/150?img=9",
    desc: "Homemade pasta from scratch! 🍝 Recipe on my blog tomorrow. Who wants the link?",
    img: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop",
    likes: ["mock1", "mock3", "mock4", "mock6", "mock8", "mock10"],
    reactions: {
      like: ["mock1", "mock3"],
      love: ["mock4", "mock6", "mock8", "mock10"],
    },
    comments: [
      {
        _id: "c7",
        userId: "mock1",
        username: "sarah_johnson",
        userProfilePic: "https://i.pravatar.cc/150?img=1",
        text: "OMG yes please! This looks incredible! 😍",
        createdAt: new Date(Date.now() - 10 * 60 * 1000),
      },
      {
        _id: "c8",
        userId: "mock4",
        username: "mike_fitness",
        userProfilePic: "https://i.pravatar.cc/150?img=13",
        text: "Need that recipe! Looks delicious!",
        createdAt: new Date(Date.now() - 5 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
  },
  {
    _id: "post6",
    userId: "mock6",
    username: "david_photo",
    userProfilePic: "https://i.pravatar.cc/150?img=14",
    desc: "Golden hour at the Grand Canyon 🌅 Nature never disappoints!",
    img: "https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800&h=600&fit=crop",
    likes: ["mock1", "mock2", "mock3", "mock5", "mock7", "mock9"],
    reactions: {
      like: ["mock1", "mock2"],
      love: ["mock3", "mock5", "mock7"],
      wow: ["mock9"],
    },
    comments: [
      {
        _id: "c9",
        userId: "mock3",
        username: "emma_creative",
        userProfilePic: "https://i.pravatar.cc/150?img=5",
        text: "Breathtaking! 📸✨",
        createdAt: new Date(Date.now() - 25 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    _id: "post7",
    userId: "mock7",
    username: "jennifer_yoga",
    userProfilePic: "https://i.pravatar.cc/150?img=16",
    desc: "Sunrise yoga session 🧘‍♀️ Start your day with gratitude and positive energy!",
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop",
    likes: ["mock4", "mock5", "mock6", "mock9"],
    reactions: {
      like: ["mock4", "mock5"],
      love: ["mock6", "mock9"],
    },
    comments: [],
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
  },
  {
    _id: "post8",
    userId: "mock8",
    username: "chris_music",
    userProfilePic: "https://i.pravatar.cc/150?img=15",
    desc: "New track dropping tonight! 🎵 Who's ready? #newmusic #producer",
    img: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop",
    likes: ["mock1", "mock3", "mock6", "mock7", "mock10"],
    reactions: {
      like: ["mock1", "mock3"],
      love: ["mock6"],
      wow: ["mock7", "mock10"],
    },
    comments: [
      {
        _id: "c10",
        userId: "mock10",
        username: "ryan_ventures",
        userProfilePic: "https://i.pravatar.cc/150?img=17",
        text: "Can't wait to hear it! 🔥",
        createdAt: new Date(Date.now() - 40 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000),
  },
  {
    _id: "post9",
    userId: "mock9",
    username: "olivia_style",
    userProfilePic: "https://i.pravatar.cc/150?img=10",
    desc: "Fall fashion essentials 🍂 Which outfit is your favorite? Comment 1, 2, or 3!",
    img: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&h=600&fit=crop",
    likes: ["mock1", "mock3", "mock5", "mock7", "mock8"],
    reactions: {
      like: ["mock1", "mock3", "mock5"],
      love: ["mock7", "mock8"],
    },
    comments: [
      {
        _id: "c11",
        userId: "mock5",
        username: "lisa_foodie",
        userProfilePic: "https://i.pravatar.cc/150?img=9",
        text: "Number 2! Love that coat! 😍",
        createdAt: new Date(Date.now() - 50 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
  },
  {
    _id: "post10",
    userId: "mock10",
    username: "ryan_ventures",
    userProfilePic: "https://i.pravatar.cc/150?img=17",
    desc: "Excited to announce our Series A funding! 🚀 Thank you to everyone who believed in our vision!",
    img: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=800&h=600&fit=crop",
    likes: ["mock1", "mock2", "mock3", "mock4", "mock5", "mock6", "mock7", "mock8"],
    reactions: {
      like: ["mock1", "mock2", "mock3", "mock4"],
      love: ["mock5", "mock6"],
      wow: ["mock7", "mock8"],
    },
    comments: [
      {
        _id: "c12",
        userId: "mock2",
        username: "alex_marvel",
        userProfilePic: "https://i.pravatar.cc/150?img=12",
        text: "Huge congrats! Well deserved! 🎉",
        createdAt: new Date(Date.now() - 60 * 60 * 1000),
      },
      {
        _id: "c13",
        userId: "mock9",
        username: "olivia_style",
        userProfilePic: "https://i.pravatar.cc/150?img=10",
        text: "Amazing news! So proud of you!",
        createdAt: new Date(Date.now() - 30 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
  },
];

// Mock Stories
export const mockStories = [
  {
    _id: "story1",
    userId: "mock1",
    username: "sarah_johnson",
    userProfilePic: "https://i.pravatar.cc/150?img=1",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=700&fit=crop",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    _id: "story2",
    userId: "mock3",
    username: "emma_creative",
    userProfilePic: "https://i.pravatar.cc/150?img=5",
    img: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=400&h=700&fit=crop",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    _id: "story3",
    userId: "mock6",
    username: "david_photo",
    userProfilePic: "https://i.pravatar.cc/150?img=14",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=700&fit=crop",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
];

